#!/bin/bash

set -e

usage() {
  echo "Usage: git wip-pull-request <branch-name>"
  exit 1
}

info() {
  message=$1
  echo -e "\033[1;34m==>\033[0;39m \033[1m${message}\033[0;39m"
}

branch_name=$1
[ -z "$branch_name" ] && usage

if ! (which hub > /dev/null 2>&1)
then
    echo "command not found: hub"
    exit 1
fi

if [ -z "$GIT_EDITOR" ]
then
    echo 'env `GIT_EDITOR` required.'
    exit 1
fi

parent_branch=$(git rev-parse --abbrev-ref HEAD)

info "Fetch origin"
git fetch --prune origin

info "Create topic branch and checkout"
git checkout -b $branch_name origin/$parent_branch

info "Create WIP commit"
git commit --allow-empty -m "[WIP][ci skip] $branch_name

TODO
----
- [ ] todo 1
- [ ] todo 2
- [ ] #issue
"

info "Push topic branch"
git push -u origin $branch_name

info "Create pull request"
hub pull-request -o -b origin/$parent_branch
