#!/bin/bash

set -e

usage() {
  echo "Usage: git wip-pull-request <branch-name>"
  exit 1
}

info() {
  message=$1
  echo -e "\033[1;34m==>\033[0;39m \033[1m${message}\033[0;39m"
}

branch_name=$1
[ -z "$branch_name" ] && usage

if ! (which hub > /dev/null 2>&1)
then
    echo "command not found: hub"
    exit 1
fi

if [ -z "$GIT_EDITOR" ]
then
    echo 'env `GIT_EDITOR` required.'
    exit 1
fi

info "Update master branch"
git checkout master
git pull --rebase --prune origin master

info "Create topic branch"
git checkout -b $branch_name

info "Create WIP commit"
git commit --allow-empty -m "[WIP][ci skip] $branch_name

TODO
----
- [ ] todo 1
- [ ] todo 2
- [ ] #issue
"

info "Push topic branch"
git push -u origin $branch_name

info "Create pull request"
hub pull-request -o
