#!/bin/sh

set -e

usage() {
  echo "Usage: git wip <branch-name>"
  exit 1
}

info() {
  message=$1
  echo "\033[1;34m==>\033[0;39m \033[1m${message}\033[0;39m"
}

branch_name=$1
[ -z "$branch_name" ] && usage

info "Update master branch"
git checkout master
git pull --rebase --prune origin master

info "Create topic branch"
git checkout -b $branch_name

info "Push topic branch"
git push -u origin $branch_name

info "Create WIP commit"
git commit --allow-empty -m "wip"
git push

info "Create pull request"
hub pull-request -o
